// <auto-generated />
namespace jobApplicationTracking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class jobapplications43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobapplications43));
        
        string IMigrationMetadata.Id
        {
            get { return "202402250137595_jobapplications43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
